name: Sync Icons

on: workflow_dispatch

jobs:
  sync:
    name: Sync Icons
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 14
        cache: 'npm'
    - name: Install Packages
      run: npm ci
    - name: Download SVG Files
      run: npm run src:download
      env:
        FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
        FIGMA_FILE: ${{ secrets.FIGMA_FILE }}
        FIGMA_PAGE: ${{ secrets.FIGMA_PAGE }}
    - name: Create TS/JS Files
      run: npm run src:icons
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: 'feat: sync icons'
        branch: sync-icons
        branch-suffix: timestamp
        delete-branch: true
        title: 'feat: sync icons'
        body: ''

